add_library(rip-hl INTERFACE)
target_compile_features(rip-hl INTERFACE cxx_std_20)
target_compile_options(rip-hl INTERFACE /clang:-ftemplate-backtrace-limit=0)
target_compile_definitions(rip-hl INTERFACE _CRT_SECURE_NO_WARNINGS=1)
target_link_libraries(rip-hl INTERFACE yyjson universal-cslib universal-cslib-reflection reflectcpp)
add_subdirectory(src)

add_executable(rip-hl-tests)
target_link_libraries(rip-hl-tests PRIVATE Catch2::Catch2WithMain rip-hl)
add_subdirectory(tests)
